version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Rome"
    commit-message:
      include: "scope"
      prefix: "deps"
      prefix-development: "devDeps"
    assignees:
      - "NotReallyEight"
    reviewers:
      - "NotReallyEight"
